// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkpoints.sql

package database

import (
	"context"
)

const getShardCheckpoint = `-- name: GetShardCheckpoint :one
SELECT shard_id, offset_value, epoch, node_id, updated_at, consumer_name, topic FROM shard_checkpoints
WHERE consumer_name = $1
  AND topic = $2
  AND shard_id = $3
`

type GetShardCheckpointParams struct {
	ConsumerName string `json:"consumer_name"`
	Topic        string `json:"topic"`
	ShardID      int32  `json:"shard_id"`
}

func (q *Queries) GetShardCheckpoint(ctx context.Context, arg GetShardCheckpointParams) (ShardCheckpoint, error) {
	row := q.db.QueryRow(ctx, getShardCheckpoint, arg.ConsumerName, arg.Topic, arg.ShardID)
	var i ShardCheckpoint
	err := row.Scan(
		&i.ShardID,
		&i.OffsetValue,
		&i.Epoch,
		&i.NodeID,
		&i.UpdatedAt,
		&i.ConsumerName,
		&i.Topic,
	)
	return i, err
}

const upsertShardCheckpoint = `-- name: UpsertShardCheckpoint :exec
INSERT INTO shard_checkpoints (
    consumer_name, topic, shard_id, offset_value, epoch, node_id, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (consumer_name, topic, shard_id) DO UPDATE SET
    offset_value = EXCLUDED.offset_value,
    epoch = EXCLUDED.epoch,
    node_id = EXCLUDED.node_id,
    updated_at = EXCLUDED.updated_at
WHERE shard_checkpoints.epoch <= EXCLUDED.epoch
`

type UpsertShardCheckpointParams struct {
	ConsumerName string `json:"consumer_name"`
	Topic        string `json:"topic"`
	ShardID      int32  `json:"shard_id"`
	OffsetValue  int64  `json:"offset_value"`
	Epoch        int64  `json:"epoch"`
	NodeID       int32  `json:"node_id"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) UpsertShardCheckpoint(ctx context.Context, arg UpsertShardCheckpointParams) error {
	_, err := q.db.Exec(ctx, upsertShardCheckpoint,
		arg.ConsumerName,
		arg.Topic,
		arg.ShardID,
		arg.OffsetValue,
		arg.Epoch,
		arg.NodeID,
		arg.UpdatedAt,
	)
	return err
}
