// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
UPDATE outbox_events
SET claimed_by = $1,
    claimed_until = $2,
    attempts = attempts + 1
WHERE event_id IN (
    SELECT event_id
    FROM outbox_events
    WHERE published_at IS NULL
      AND outbox_events.claimed_until < $3
    ORDER BY occurred_at
    FOR UPDATE SKIP LOCKED
    LIMIT $4
)
RETURNING event_id, event_type, aggregate_type, aggregate_id, shard_id, occurred_at, payload, published_at, topic, message_key, claimed_by, claimed_until, attempts, last_error
`

type ClaimOutboxEventsParams struct {
	WorkerID   string `json:"worker_id"`
	LeaseUntil int64  `json:"lease_until"`
	NowValue   int64  `json:"now_value"`
	BatchSize  int32  `json:"batch_size"`
}

func (q *Queries) ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents,
		arg.WorkerID,
		arg.LeaseUntil,
		arg.NowValue,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.EventID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.ShardID,
			&i.OccurredAt,
			&i.Payload,
			&i.PublishedAt,
			&i.Topic,
			&i.MessageKey,
			&i.ClaimedBy,
			&i.ClaimedUntil,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (
    event_id, event_type, aggregate_type, aggregate_id,
    shard_id, occurred_at, payload, topic, message_key
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (event_id) DO NOTHING
`

type CreateOutboxEventParams struct {
	EventID       string `json:"event_id"`
	EventType     string `json:"event_type"`
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
	ShardID       int32  `json:"shard_id"`
	OccurredAt    int64  `json:"occurred_at"`
	Payload       []byte `json:"payload"`
	Topic         string `json:"topic"`
	MessageKey    string `json:"message_key"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.ShardID,
		arg.OccurredAt,
		arg.Payload,
		arg.Topic,
		arg.MessageKey,
	)
	return err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET claimed_by = '',
    claimed_until = 0,
    last_error = $2
WHERE event_id = $1
  AND claimed_by = $3
`

type MarkOutboxEventFailedParams struct {
	EventID   string `json:"event_id"`
	LastError string `json:"last_error"`
	ClaimedBy string `json:"claimed_by"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.EventID, arg.LastError, arg.ClaimedBy)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET published_at = $2,
    claimed_by = '',
    claimed_until = 0,
    last_error = ''
WHERE event_id = $1
  AND claimed_by = $3
`

type MarkOutboxEventPublishedParams struct {
	EventID     string      `json:"event_id"`
	PublishedAt pgtype.Int8 `json:"published_at"`
	ClaimedBy   string      `json:"claimed_by"`
}

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, arg MarkOutboxEventPublishedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, arg.EventID, arg.PublishedAt, arg.ClaimedBy)
	return err
}

const recordInboxEvent = `-- name: RecordInboxEvent :execrows
INSERT INTO inbox_events (consumer_name, event_id, shard_id, offset_value, processed_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (consumer_name, event_id) DO NOTHING
`

type RecordInboxEventParams struct {
	ConsumerName string `json:"consumer_name"`
	EventID      string `json:"event_id"`
	ShardID      int32  `json:"shard_id"`
	OffsetValue  int64  `json:"offset_value"`
	ProcessedAt  int64  `json:"processed_at"`
}

func (q *Queries) RecordInboxEvent(ctx context.Context, arg RecordInboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordInboxEvent,
		arg.ConsumerName,
		arg.EventID,
		arg.ShardID,
		arg.OffsetValue,
		arg.ProcessedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
