// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InboxEvent struct {
	EventID      string `json:"event_id"`
	ShardID      int32  `json:"shard_id"`
	OffsetValue  int64  `json:"offset_value"`
	ProcessedAt  int64  `json:"processed_at"`
	ConsumerName string `json:"consumer_name"`
}

type Order struct {
	OrderID      int64  `json:"order_id"`
	ShardID      int32  `json:"shard_id"`
	Status       string `json:"status"`
	X            int32  `json:"x"`
	Y            int32  `json:"y"`
	Attempt      int32  `json:"attempt"`
	CancelReason string `json:"cancel_reason"`
	RetryReason  string `json:"retry_reason"`
	MissReason   string `json:"miss_reason"`
	RiderID      int64  `json:"rider_id"`
	Score        int32  `json:"score"`
	LastEventID  string `json:"last_event_id"`
	UpdatedAt    int64  `json:"updated_at"`
}

type OutboxEvent struct {
	EventID       string      `json:"event_id"`
	EventType     string      `json:"event_type"`
	AggregateType string      `json:"aggregate_type"`
	AggregateID   string      `json:"aggregate_id"`
	ShardID       int32       `json:"shard_id"`
	OccurredAt    int64       `json:"occurred_at"`
	Payload       []byte      `json:"payload"`
	PublishedAt   pgtype.Int8 `json:"published_at"`
	Topic         string      `json:"topic"`
	MessageKey    string      `json:"message_key"`
	ClaimedBy     string      `json:"claimed_by"`
	ClaimedUntil  int64       `json:"claimed_until"`
	Attempts      int32       `json:"attempts"`
	LastError     string      `json:"last_error"`
}

type Rider struct {
	Uid    int64 `json:"uid"`
	X      int32 `json:"x"`
	Y      int32 `json:"y"`
	Online bool  `json:"online"`
	CellID int64 `json:"cell_id"`
	Count  int64 `json:"count"`
}

type ShardCheckpoint struct {
	ShardID      int32  `json:"shard_id"`
	OffsetValue  int64  `json:"offset_value"`
	Epoch        int64  `json:"epoch"`
	NodeID       int32  `json:"node_id"`
	UpdatedAt    int64  `json:"updated_at"`
	ConsumerName string `json:"consumer_name"`
	Topic        string `json:"topic"`
}
