// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package database

import (
	"context"
)

const getOrder = `-- name: GetOrder :one
SELECT order_id, shard_id, status, x, y, attempt, cancel_reason, retry_reason, miss_reason, rider_id, score, last_event_id, updated_at FROM orders
WHERE order_id = $1
`

func (q *Queries) GetOrder(ctx context.Context, orderID int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.ShardID,
		&i.Status,
		&i.X,
		&i.Y,
		&i.Attempt,
		&i.CancelReason,
		&i.RetryReason,
		&i.MissReason,
		&i.RiderID,
		&i.Score,
		&i.LastEventID,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT order_id, shard_id, status, x, y, attempt, cancel_reason, retry_reason, miss_reason, rider_id, score, last_event_id, updated_at FROM orders
WHERE order_id = $1
FOR UPDATE
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, orderID int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.ShardID,
		&i.Status,
		&i.X,
		&i.Y,
		&i.Attempt,
		&i.CancelReason,
		&i.RetryReason,
		&i.MissReason,
		&i.RiderID,
		&i.Score,
		&i.LastEventID,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderMatched = `-- name: MarkOrderMatched :execrows
UPDATE orders
SET status = 'matched',
    rider_id = $2,
    score = $3,
    last_event_id = $4,
    updated_at = $5
WHERE order_id = $1
  AND status = 'match_pending'
`

type MarkOrderMatchedParams struct {
	OrderID     int64  `json:"order_id"`
	RiderID     int64  `json:"rider_id"`
	Score       int32  `json:"score"`
	LastEventID string `json:"last_event_id"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) MarkOrderMatched(ctx context.Context, arg MarkOrderMatchedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderMatched,
		arg.OrderID,
		arg.RiderID,
		arg.Score,
		arg.LastEventID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOrderMissed = `-- name: MarkOrderMissed :execrows
UPDATE orders
SET status = 'missed',
    miss_reason = $2,
    last_event_id = $3,
    updated_at = $4
WHERE order_id = $1
  AND status = 'match_pending'
`

type MarkOrderMissedParams struct {
	OrderID     int64  `json:"order_id"`
	MissReason  string `json:"miss_reason"`
	LastEventID string `json:"last_event_id"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) MarkOrderMissed(ctx context.Context, arg MarkOrderMissedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderMissed,
		arg.OrderID,
		arg.MissReason,
		arg.LastEventID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertOrder = `-- name: UpsertOrder :exec
INSERT INTO orders (
    order_id, shard_id, status, x, y, attempt,
    cancel_reason, retry_reason, miss_reason,
    rider_id, score, last_event_id, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (order_id) DO UPDATE SET
    shard_id = EXCLUDED.shard_id,
    status = EXCLUDED.status,
    x = EXCLUDED.x,
    y = EXCLUDED.y,
    attempt = EXCLUDED.attempt,
    cancel_reason = EXCLUDED.cancel_reason,
    retry_reason = EXCLUDED.retry_reason,
    miss_reason = EXCLUDED.miss_reason,
    rider_id = EXCLUDED.rider_id,
    score = EXCLUDED.score,
    last_event_id = EXCLUDED.last_event_id,
    updated_at = EXCLUDED.updated_at
`

type UpsertOrderParams struct {
	OrderID      int64  `json:"order_id"`
	ShardID      int32  `json:"shard_id"`
	Status       string `json:"status"`
	X            int32  `json:"x"`
	Y            int32  `json:"y"`
	Attempt      int32  `json:"attempt"`
	CancelReason string `json:"cancel_reason"`
	RetryReason  string `json:"retry_reason"`
	MissReason   string `json:"miss_reason"`
	RiderID      int64  `json:"rider_id"`
	Score        int32  `json:"score"`
	LastEventID  string `json:"last_event_id"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) UpsertOrder(ctx context.Context, arg UpsertOrderParams) error {
	_, err := q.db.Exec(ctx, upsertOrder,
		arg.OrderID,
		arg.ShardID,
		arg.Status,
		arg.X,
		arg.Y,
		arg.Attempt,
		arg.CancelReason,
		arg.RetryReason,
		arg.MissReason,
		arg.RiderID,
		arg.Score,
		arg.LastEventID,
		arg.UpdatedAt,
	)
	return err
}
