// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error
	GetOrder(ctx context.Context, orderID int64) (Order, error)
	GetOrderForUpdate(ctx context.Context, orderID int64) (Order, error)
	GetRider(ctx context.Context, uid int64) (Rider, error)
	GetShardCheckpoint(ctx context.Context, arg GetShardCheckpointParams) (ShardCheckpoint, error)
	ListMissedOrdersForRetry(ctx context.Context, arg ListMissedOrdersForRetryParams) ([]ListMissedOrdersForRetryRow, error)
	MarkOrderMatched(ctx context.Context, arg MarkOrderMatchedParams) (int64, error)
	MarkOrderMissed(ctx context.Context, arg MarkOrderMissedParams) (int64, error)
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error
	MarkOutboxEventPublished(ctx context.Context, arg MarkOutboxEventPublishedParams) error
	MarkOutboxEventsPublished(ctx context.Context, arg MarkOutboxEventsPublishedParams) (int64, error)
	RecordInboxEvent(ctx context.Context, arg RecordInboxEventParams) (int64, error)
	ReserveRider(ctx context.Context, arg ReserveRiderParams) (Rider, error)
	UpsertOrder(ctx context.Context, arg UpsertOrderParams) error
	UpsertRider(ctx context.Context, arg UpsertRiderParams) error
	UpsertShardCheckpoint(ctx context.Context, arg UpsertShardCheckpointParams) error
}

var _ Querier = (*Queries)(nil)
