// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: riders.sql

package database

import (
	"context"
)

const getRider = `-- name: GetRider :one
SELECT uid, x, y, online, cell_id, count FROM riders
WHERE uid = $1
`

func (q *Queries) GetRider(ctx context.Context, uid int64) (Rider, error) {
	row := q.db.QueryRow(ctx, getRider, uid)
	var i Rider
	err := row.Scan(
		&i.Uid,
		&i.X,
		&i.Y,
		&i.Online,
		&i.CellID,
		&i.Count,
	)
	return i, err
}

const reserveRider = `-- name: ReserveRider :one
UPDATE riders
SET count = count + 1
WHERE uid = $1
  AND online = TRUE
  AND count < $2
RETURNING uid, x, y, online, cell_id, count
`

type ReserveRiderParams struct {
	Uid      int64 `json:"uid"`
	MaxCount int64 `json:"max_count"`
}

func (q *Queries) ReserveRider(ctx context.Context, arg ReserveRiderParams) (Rider, error) {
	row := q.db.QueryRow(ctx, reserveRider, arg.Uid, arg.MaxCount)
	var i Rider
	err := row.Scan(
		&i.Uid,
		&i.X,
		&i.Y,
		&i.Online,
		&i.CellID,
		&i.Count,
	)
	return i, err
}

const upsertRider = `-- name: UpsertRider :exec
INSERT INTO riders (uid, x, y, online, cell_id, count)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (uid) DO UPDATE SET
    x = EXCLUDED.x,
    y = EXCLUDED.y,
    online = EXCLUDED.online,
    cell_id = EXCLUDED.cell_id,
    count = EXCLUDED.count
`

type UpsertRiderParams struct {
	Uid    int64 `json:"uid"`
	X      int32 `json:"x"`
	Y      int32 `json:"y"`
	Online bool  `json:"online"`
	CellID int64 `json:"cell_id"`
	Count  int64 `json:"count"`
}

func (q *Queries) UpsertRider(ctx context.Context, arg UpsertRiderParams) error {
	_, err := q.db.Exec(ctx, upsertRider,
		arg.Uid,
		arg.X,
		arg.Y,
		arg.Online,
		arg.CellID,
		arg.Count,
	)
	return err
}
